%[predictions, confidence, votes, exemplarindices, constituentclusters] = ACORN_consensus (csvfolder)
%
%ARGUMENTS: 
%csvfolder should be the path to a folder containing ACORN-iteration*.csv files generated by ACORN_generate.py
%
%optionally, the tolerance threshold can be set as the second argument (the default and recommended value is 2.0; values within a range of 1.5 to 3.0 are sensible).
%setting a tolerance threshold of NaN will force the method to classify as many neurons as possible with no regard for confidence (not recommended)
%consensus predictions of "uncertain" (-1) may appear when none of the constituent clusterings classified a neuron, or its final assignment would be below the confidence threshold
%
%RETURN VALUES:
%returns an array of consensus predictions.
%
%optionally, returns confidence values (2nd return value)
%optionally, returns the "V" matrix of votes (3rd return value)
%optionally, returns the indices of the exemplars (4th return value)
%optionally, returns each constituent clustering (5th return value)

function [predictions, varargout] = ACORN_consensus(csvfolder, varargin)
    
    if nargin >= 2
        tolerance = varargin{1};
    else
        tolerance = 2;
    end
    
    CONST_UNCLASSIFIED = -1;
    
    ACORNiterationfiles = dir(fullfile(csvfolder, 'ACORN-iteration*.csv'));
    [~, sortindices] = sort([ACORNiterationfiles.datenum]); %sort in order of creation, so that e.g. 10 does not come before 2, as it would if sorted alphanumerically.
    ACORNiterationfiles = {ACORNiterationfiles(sortindices).name};

    iterationn = numel(ACORNiterationfiles);
    
    warning('off', 'MATLAB:table:ModifiedAndSavedVarnames'); %harmless, would otherwise spam the console while reading Python-generated csv tables
    for iterationi=1:iterationn
        currentfullfile = fullfile(csvfolder, ACORNiterationfiles{iterationi});
        importoptions = detectImportOptions(currentfullfile, ReadVariableNames=true);
        pythontable = readtable(fullfile(csvfolder, ACORNiterationfiles{iterationi}), importoptions);

        clustercolumn = strcmpi(pythontable.Properties.VariableNames, 'cluster');

        if iterationi==1
            neuronn = size(pythontable, 1);
            HDBSCANclusters = NaN(iterationn, neuronn);
        end

        HDBSCANclusters(iterationi, :) = pythontable{:, clustercolumn}';
    end

    clusternumbers = max(HDBSCANclusters, [], 2, 'omitmissing') + 1; %in the tables, -1 denotes unclustered and 0 denotes a valid cluster, so the number of real clusters is max+1
    expectedclustern = max(clusternumbers, [], 'omitmissing');
    %clusternumbers = clusternumbers(clusternumbers>0);
    %clusternumbers = sort(clusternumbers, 'ascend');
    %expectedclustern = clusternumbers(round(numel(clusternumbers)*0.95, TieBreaker="even")); %95th percentile
    
    exemplarindices = NaN(1, neuronn);
    for currentexemplari=1:neuronn
        Svalue = int64(zeros(1, neuronn));
        for iterationi=1:iterationn
            for clusteri=min(HDBSCANclusters(iterationi, :), [], 'omitmissing'):max(HDBSCANclusters(iterationi, :), [], 'omitmissing')
                if clusteri == CONST_UNCLASSIFIED, continue, end
                currentgroupmembers = find(HDBSCANclusters(iterationi, :) == clusteri);
                currentgroupsize = numel(currentgroupmembers);
                clashes = sum(ismember(exemplarindices, currentgroupmembers));

                if clashes == 0
                    toadd = currentgroupsize;
                else
                    toadd = round(-clashes * neuronn/expectedclustern/2, TieBreaker="even"); %rounding because we're using int64 for Svalue because the accumulated values can get very big with large numbers of neurons
                end

                Svalue(currentgroupmembers) = Svalue(currentgroupmembers) + toadd;
            end
        end
        [maxvalue, maxwhere] = max(Svalue);
        if maxvalue > 0
            exemplarindices(currentexemplari) = maxwhere;
        else
            break
        end
    end
    exemplarindices = exemplarindices(~isnan(exemplarindices));
    exemplarn = numel(exemplarindices);
    CONST_UNCERTAIN = exemplarn + 1;
    
    % we want votes to include an "uncertain" (none of the above) cluster because confidence will be the ratio of the highest and second-highest votes;
    % example: with 2 votes for A, 1 vote for B, and 97 votes for "none of the above", the result should NOT be "A with a confidence of 2.0" but "uncertain"
    % that is why we measure the number of times a neuron was unclassified in constituent clusterings
    votes = zeros(neuronn, exemplarn+1); %the actual consensus clusters go from 1 to exemplarn; exemplarn+1 denotes "uncertain"
    for iterationi=1:iterationn
        for clusteri=min(HDBSCANclusters(iterationi, :), [], 'omitmissing'):max(HDBSCANclusters(iterationi, :), [], 'omitmissing')
            currentgroupmembers = find(HDBSCANclusters(iterationi, :) == clusteri);
            if clusteri == CONST_UNCLASSIFIED
                votes(currentgroupmembers, CONST_UNCERTAIN) = votes(currentgroupmembers, CONST_UNCERTAIN) + 1;
            else
                whichexemplars = find(ismember(exemplarindices, currentgroupmembers));
                votes(currentgroupmembers, whichexemplars) = votes(currentgroupmembers, whichexemplars) + 1/numel(whichexemplars); %splitting the votes equally between exemplars present in the cluster
            end
        end
    end
    votes(:, CONST_UNCERTAIN) = votes(:, CONST_UNCERTAIN)/2; %disagreement between "cell type A" and "uncertain" should hurt the consensus less than disagreement between "cell type A" and "cell type B"

    predictions = ones(1, neuronn) * CONST_UNCLASSIFIED;
    
    confidence = NaN(1, neuronn);
    for neuroni=1:neuronn
        [sortedvotevalues, sortedvoteindices] = sort(votes(neuroni, :), 'descend');
        if sortedvoteindices(1) == CONST_UNCERTAIN
            confidence(neuroni) = 0;
        else
            confidence(neuroni) = sortedvotevalues(1) / sortedvotevalues(2);
        end
        if ~isnan(tolerance) % Calculating the consensus result with a minimum threshold for agreement.
            if confidence(neuroni) >= tolerance && confidence(neuroni) > 1 && sortedvoteindices(1) ~= CONST_UNCERTAIN %a confidence value of _exactly 1_ means that there was a tie for first place, meaning predicting one or the other would be a matter of pure chance, so we'll leave it as uncertain in that case
                predictions(neuroni) = sortedvoteindices(1);
            end
        end
    end
    if isnan(tolerance) %still want to calculate confidence even when tolerance is set to NaN, which is why this is not under some kind of else block
        % Forced classification instead
        for neuroni=1:neuronn
            [howgood, whichbest] = max(votes(neuroni, 1:exemplarn));
            if howgood > 0 %it may still turn out, even using forced classification, that literally all constituent clusterings failed to classify it. In that case we still have no way to assign it to any consensus cluster.
                predictions(neuroni) = whichbest;
            end
        end
        % Singleton clusters are effectively the same as unclassified. This should only occur with the forced classification method (which is not recommended anyway)
        % Actually, to ensure that all neurons are classified when using forced classification (that's the whole point of it), we'll let there be singleton clusters (even though that's basically equivalent to setting them unclassified, except even worse when assessing classification performance)
        %for i=1:exemplarn
        %    if sum(predictions == i) == 1
        %        predictions(predictions==i) = CONST_UNCLASSIFIED;
        %    end
        %end
    end
    
    
    if nargout >= 2
        varargout{1} = confidence;
    end
    if nargout >= 3
        varargout{2} = votes;
    end
    if nargout >= 4
        varargout{3} = exemplarindices;
    end
    if nargout >= 5
        varargout{4} = HDBSCANclusters;
    end
    
end
